### ISSUE TITLE
[Feat] home 화면의 items list View 작업

### ISSUE THREAD

**Issue by wjdsheep15** [ASAC04-A-Team/airbnb-clone-project-front#34]
## ISSUE
home화면의 items list View 구현

## ESTIMATE
Day-3

## TASKS
- [x] item CardView 구현
- [x] image data fetch로 가져와 cardView에 적용
- [x] item의 주소기준 거리 판별 구현
- [x] 게스트 선호 구현
 
- [x] 일박의 가격
- [x] 리뷰 개수 구하기

**Comment by wjdsheep15** [comment]
일단 구현을 완료하였습니다.
